name: Deploy API to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'shared/**'
      - '.github/workflows/api-deploy.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: msp-sap-api2  # Updated to your actual app name
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Create directory structure
      run: |
        mkdir -p api/shared
        cp -r shared/* api/shared/
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
        
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./api